functionsDirectory = "C:\\Users\\kumar\\OneDrive\\Desktop\\MasterResume\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
plugins = []
headers = []
redirects = []

[build]
publish = "C:\\Users\\kumar\\OneDrive\\Desktop\\MasterResume\\dist"
publishOrigin = "config"
commandOrigin = "config"
command = "node build-deploy.js"
functions = "C:\\Users\\kumar\\OneDrive\\Desktop\\MasterResume\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]