functionsDirectory = "C:\\Users\\kumar\\OneDrive\\Desktop\\MasterResume\\netlify\\functions"
functionsDirectoryOrigin = "default"
plugins = []
headers = []
redirects = []

[build]
publish = "C:\\Users\\kumar\\OneDrive\\Desktop\\MasterResume"
publishOrigin = "default"
base = "C:\\Users\\kumar\\OneDrive\\Desktop\\MasterResume"
functions = "C:\\Users\\kumar\\OneDrive\\Desktop\\MasterResume\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]